import com.typesafe.sbt.web.Import.WebKeys.assets
import play.sbt.routes.RoutesKeys
import sbt.Keys.javaOptions
import scoverage.ScoverageKeys
import uk.gov.hmrc.DefaultBuildSettings.{addTestReportOption, defaultSettings, scalaSettings}
import uk.gov.hmrc.sbtdistributables.SbtDistributablesPlugin
import uk.gov.hmrc.sbtsettingkeys.Keys.isPublicArtefact


lazy val appName: String = "add-taxes-frontend"
lazy val plugins: Seq[Plugins] = Seq.empty
lazy val playSettings: Seq[Setting[?]] = Seq(
  RoutesKeys.routesImport ++= Seq(),
  TwirlKeys.templateImports ++= Seq(
    "uk.gov.hmrc.govukfrontend.views.html.components._",
    "uk.gov.hmrc.hmrcfrontend.views.html.{components => hmrcComponents}"
  )
)

def unitFilter(name: String): Boolean = name startsWith "unit"

def getSourceDirectories(root: File, testType: String) = Seq(root / s"test/$testType")
def getResourceDirectories(root: File, testType: String) = Seq(root / s"test/$testType", root / "target/web/public/test")

lazy val microservice = Project(appName, file("."))
  .enablePlugins((Seq(play.sbt.PlayScala, SbtDistributablesPlugin) ++ plugins) *)
  .disablePlugins(JUnitXmlReportPlugin)
  .settings(playSettings: _*)
  .settings(RoutesKeys.routesImport ++= Seq(
    "models._",
    "config.Binders._",
    "testonly.FeatureQueryBinder._"
  ))
  .settings(
    ScoverageKeys.coverageExcludedFiles := "<empty>;Reverse.*;.*filters.*;.*handlers.*;.*components.*;.*models.*;.*identifiers.*;.*repositories.*;" +
      ".*BuildInfo.*;.*javascript.*;.*FrontendAuditConnector.*;.*Routes.*;.*GuiceInjector;.*DataCacheConnector;" +
      ".*ControllerConfiguration;.*LanguageSwitchController;.*FeatureQueryBinder;.*featureToggles;.*feature_switch;.*FeatureSwitchController.*",
    ScoverageKeys.coverageMinimumStmtTotal := 92.98,
    ScoverageKeys.coverageFailOnMinimum := true,
    ScoverageKeys.coverageHighlighting := true,
    parallelExecution in Test := false
  )
  .settings(scalaSettings: _*)
  .settings(defaultSettings(): _*)
  .settings(
    scalaVersion := "2.13.16",
    libraryDependencies ++= AppDependencies(),
    retrieveManaged := true,
    PlayKeys.playDefaultPort := 9730,
    isPublicArtefact := true
  )
  .settings(inConfig(Test)(Defaults.testSettings): _*)
  .settings(
    addTestReportOption(Test, "test-reports"),
    unmanagedSourceDirectories in Test := (baseDirectory in Test) (base => getSourceDirectories(base, "unit")).value,
    unmanagedResourceDirectories in Test := (baseDirectory in Test) (base => getResourceDirectories(base, "unit")).value
  )
  .configs(IntegrationTest)
  .settings(inConfig(IntegrationTest)(Defaults.itSettings): _*)
  .settings(
    unmanagedSourceDirectories in IntegrationTest := (baseDirectory in IntegrationTest) (base => getSourceDirectories(base, "it")).value,
    unmanagedResourceDirectories in IntegrationTest := (baseDirectory in IntegrationTest) (base => getResourceDirectories(base, "it")).value,
    Keys.fork in IntegrationTest := true,
    parallelExecution in IntegrationTest := false,
    addTestReportOption(IntegrationTest, "it-test-reports"),
    (compile in IntegrationTest) := (compile in IntegrationTest).dependsOn(assets in TestAssets).value,
    unmanagedClasspath in IntegrationTest += ((baseDirectory in IntegrationTest) map { base => Attributed.blank(base / "target/web/public/test") }).value,
    javaOptions in IntegrationTest ++= Seq(
      "-Dlogger.resource=logback-test.xml"
    )
  )
  .settings(
    Keys.fork in Test := true,
    Keys.fork in IntegrationTest := true,
    addTestReportOption(IntegrationTest, "int-test-reports"),
    parallelExecution in IntegrationTest := false
  )
  .settings(
    // concatenate js
    Concat.groups := Seq(
      "javascripts/addtaxesfrontend-app.js" -> group(Seq("javascripts/show-hide-content.js"))
    ),
    // prevent removal of unused code which generates warning errors due to use of third-party libs
    uglifyCompressOptions := Seq("unused=false", "dead_code=false"),
    pipelineStages := Seq(digest),
    // below line required to force asset pipeline to operate in dev rather than only prod
    pipelineStages in Assets := Seq(concat, uglify),
    // only compress files generated by concat
    includeFilter in uglify := GlobFilter("addtaxesfrontend-*.js"))
  .settings(majorVersion := 0)
