import com.typesafe.sbt.web.Import.WebKeys.assets
import play.sbt.routes.RoutesKeys
import sbt.Keys.javaOptions
import scoverage.ScoverageKeys
import uk.gov.hmrc.DefaultBuildSettings.{addTestReportOption, defaultSettings, scalaSettings}
import uk.gov.hmrc.sbtdistributables.SbtDistributablesPlugin
import uk.gov.hmrc.sbtsettingkeys.Keys.isPublicArtefact

lazy val appName: String       = "add-taxes-frontend"
lazy val plugins: Seq[Plugins] = Seq.empty
lazy val playSettings: Seq[Setting[?]] = Seq(
  RoutesKeys.routesImport ++= Seq(),
  TwirlKeys.templateImports ++= Seq(
    "uk.gov.hmrc.govukfrontend.views.html.components._",
    "uk.gov.hmrc.hmrcfrontend.views.html.{components => hmrcComponents}"
  )
)

def unitFilter(name: String): Boolean = name startsWith "unit"

def getSourceDirectories(root: File, testType: String)   = Seq(root / s"test/$testType")
def getResourceDirectories(root: File, testType: String) = Seq(root / s"test/$testType", root / "target/web/public/test")

lazy val microservice = Project(appName, file("."))
  .enablePlugins((Seq(play.sbt.PlayScala, SbtDistributablesPlugin) ++ plugins) *)
  .disablePlugins(JUnitXmlReportPlugin)
  .settings(playSettings *)
  .settings(RoutesKeys.routesImport ++= Seq(
    "models._",
    "config.Binders._",
    "testonly.FeatureQueryBinder._"
  ))
  .settings(
    ScoverageKeys.coverageExcludedFiles := "<empty>;Reverse.*;.*filters.*;.*handlers.*;.*components.*;.*models.*;.*identifiers.*;.*repositories.*;" +
      ".*BuildInfo.*;.*javascript.*;.*FrontendAuditConnector.*;.*Routes.*;.*GuiceInjector;.*DataCacheConnector;" +
      ".*ControllerConfiguration;.*LanguageSwitchController;.*FeatureQueryBinder;.*featureToggles;.*feature_switch;.*FeatureSwitchController.*",
    ScoverageKeys.coverageMinimumStmtTotal := 92.98,
    ScoverageKeys.coverageFailOnMinimum    := true,
    ScoverageKeys.coverageHighlighting     := true,
    Test / parallelExecution               := false
  )
  .settings(scalaSettings *)
  .settings(defaultSettings() *)
  .settings(
    scalaVersion := "2.13.16",
    libraryDependencies ++= AppDependencies(),
    retrieveManaged          := true,
    PlayKeys.playDefaultPort := 9730,
    isPublicArtefact         := true
  )
  .settings(inConfig(Test)(Defaults.testSettings) *)
  .settings(
    addTestReportOption(Test, "test-reports"),
    Test / unmanagedSourceDirectories   := (Test / baseDirectory)(base => getSourceDirectories(base, "unit")).value,
    Test / unmanagedResourceDirectories := (Test / baseDirectory)(base => getResourceDirectories(base, "unit")).value
  )
  .configs(IntegrationTest)
  .settings(inConfig(IntegrationTest)(Defaults.itSettings) *)
  .settings(
    IntegrationTest / unmanagedSourceDirectories   := (IntegrationTest / baseDirectory)(base => getSourceDirectories(base, "it")).value,
    IntegrationTest / unmanagedResourceDirectories := (IntegrationTest / baseDirectory)(base => getResourceDirectories(base, "it")).value,
    IntegrationTest / Keys.fork                    := true,
    IntegrationTest / parallelExecution            := false,
    addTestReportOption(IntegrationTest, "it-test-reports"),
    (IntegrationTest / compile) := (IntegrationTest / compile).dependsOn(TestAssets / assets).value,
    IntegrationTest / unmanagedClasspath += ((IntegrationTest / baseDirectory) map { base =>
      Attributed.blank(base / "target/web/public/test")
    }).value,
    IntegrationTest / javaOptions ++= Seq(
      "-Dlogger.resource=logback-test.xml"
    ),
    scalacOptions.+=("-Wconf:src=routes/.*:s"),
    scalacOptions.+=("-Wconf:src=html/.*:s")
  )
  .settings(
    Test / Keys.fork            := true,
    IntegrationTest / Keys.fork := true,
    addTestReportOption(IntegrationTest, "int-test-reports"),
    IntegrationTest / parallelExecution := false
  )
  .settings(
    // concatenate js
    Concat.groups := Seq(
      "javascripts/addtaxesfrontend-app.js" -> group(Seq("javascripts/show-hide-content.js"))
    ),
    // prevent removal of unused code which generates warning errors due to use of third-party libs
    uglifyCompressOptions := Seq("unused=false", "dead_code=false"),
    uglifyOps             := UglifyOps.singleFile,
    pipelineStages        := Seq(digest),
    // below line required to force asset pipeline to operate in dev rather than only prod
    Assets / pipelineStages := Seq(concat, uglify),
    // only compress files generated by concat
    uglify / includeFilter := GlobFilter("addtaxesfrontend-*.js")
  )
  .settings(majorVersion := 0)
